- name: Install Skype
  apt: pkg=skype state=installed

- name: Does the Google apt file exist?
  command: test -f {{ google_talk_apt_file }}
  register: google_talk_apt_exists
  ignore_errors: true

- name: Add Google Talk repo
  copy: content="deb http://dl.google.com/linux/talkplugin/deb/ stable main" dest={{ google_talk_apt_file }} owner=root group=root mode=644
  when: google_talk_apt_exists.rc == 1

- name: Update apt cache
  apt: update_cache=yes
  when: google_talk_apt_exists.rc == 1

- name: Install Google Hangouts plugin
  apt: pkg=google-talkplugin state=installed