- name: Install improved and specialised versions of 'top'
  apt: pkg={{ item }} state=installed
  with_items:
    - htop
    - iotop
    - powertop

- name: Install GParted
  apt: pkg=gparted state=installed

- name: Install unetbootin
  apt: pkg=unetbootin state=installed

- name: Install tree for an overview version of "ls"
  apt: pkg=tree state=installed

- name: Install cURL
  apt: pkg=curl state=installed

- name: Install inotify
  apt: pkg=inotify-tools state=installed

- name: Install system monitors for applets
  apt: pkg={{ item }} state=installed
  with_items:
    - vnstat
    - vnstati
    - gir1.2-gtop-2.0

- name: Install supervisor
  apt: pkg=supervisor state=installed
