- name: Install Android tools
  apt: pkg={{ item }} state=installed
  with_items:
    - android-tools-adb
    - android-tools-fastboot

- name: Install Android SDK
  apt: pkg={{ item }} state=installed
  with_items:
    - androidsdk-ddms
    - androidsdk-hierarchyviewer
    - androidsdk-traceview
    - androidsdk-uiautomatorviewer

- name: Install Java via OpenJDK
  apt: pkg=openjdk-7-jdk state=installed

- name: Install ant for building APKs
  apt: pkg=ant state=installed
