- name: Install NodeJS
  apt: pkg=nodejs state=installed

- name: Install NodeJS's package manager
  apt: pkg=npm state=installed

- name: Install PhantomJS
  apt: pkg=phantomjs state=installed

- name: Install useful npm modules
  shell: npm -g install {{ item }}
  with_items:
    - casperjs
    - slimerjs
    - jshint