- name: Install Python
  apt: pkg=python state=installed

- name: Install Python's package managers
  apt: pkg=python-pip state=installed

- name: Install pylint
  apt: pkg=pylint state=installed

- name: mitmproxy library dependencies
  apt: pkg={{ item }} state=installed
  with_items:
    - libxml2-dev
    - libxslt-dev

- name: Install Pip modules
  shell: pip install {{ item }}
  with_items:
    - mitmproxy
    - mock

- name: Install Python3
  apt: pkg=python3 state=installed

- name: Install Python3's package managers
  apt: pkg=python3-pip state=installed
