- name: Install useful terminals
  apt: pkg={{ item }} state=installed
  with_items:
    - terminator
    - guake

- name: Setup my custom .bashrc
  template: src=bashrc.j2 dest=~/.bashrc

- name: Install screen
  apt: pkg=screen state=installed
