- name: Install whois client
  apt: pkg=whois state=installed

- name: Install bandwidth monitor
  apt: pkg=bwm-ng state=installed

- name: Install unrar-er
  apt: pkg=rar state=installed

- name: cURL development packages
  apt: pkg=libcurl4-openssl-dev state=installed
